const jsonata = require('jsonata');

module.exports.getExpression = function(msg) {
  const expression = {
    // "firstname": msg.body.firstName,
    // "name": msg.body.lastName,
    "updated_date": jsonata("$now()").evaluate(),
    "address_category2": "",
    "phone": 712372346,
    "wp_contact_remote_addr": "",
    "phone3": 712372346,
    "status_date": "",
    "picture": "",
    "company": "",
    "line_category2": "",
    "address_location_formatted": "",
    "private_email": "",
    "colspan": "",
    "email_check_result": "",
    "address_category1": " ",
    "private_street_number": "",
    "mandant": "",
    "position": "",
    "private_state": "HH",
    "private_country_symbol": "",
    "mobile_phone": "",
    "email_save_note": "",
    "updated_by_user": "",
    "rowid": msg.body.applicationRecordUid,
    "oldstatus_remarks": "",
    "picture_url": msg.body.photo,
    "deactivated": "",
    "delete_link": "",
    "serial_salutation": "",
    "house_post_code": "",
    "history_log": "",
    "for_table": "",
    "class_name": "",
    "firstname": msg.body.firstName,
    "standard_person": "",
    "same_contactperson": "",
    "status_time": "",
    "column_header": "",
    "private_email_save_note": "",
    "private_phone": 135792468,
    "private_street": "Test Str 15",
    "updated_time": "",
    "detail": "",
    "eternal_exclusion_from_all_mailinglists": "",
    "privphone": 1234566,
    "status_locked": "",
    "address_category3": "",
    "birthday": msg.body.birthday,
    "remarks": "",
    "column_output": "",
    "fax": 9876543,
    "caring_employee": "",
    "last_update": oihApplicationRecords.lastModified,
    "address_category4": "",
    "created_by_wp_contact": "0",
    "salutation": msg.body.salutation,
    "updated_by_user_group": "",
    "phone2": "",
    "oldstatus": "",
    "title": msg.body.title,
    "private_country": "Deutschland",
    "private_mobile_phone": "",
    "private_zip_code": 20537,
    "name": msg.body.lastName,
    "import_key": "",
    "xing_url": "www.xing.com/test",
    "url": "www.mywebsite.com",
    "email": "test@mail.com",
    "line_category1": "",
    "private_town": "Hamburg Borgfelde",
    "department": "",
    "for_rowid": 199978

  };
  return expression;
}
